version: '3.8'

services:
  kode:
    build: .
    image: kode:latest
    hostname: kode
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
